[basic]
	#Defined the max amount of running recipes
	# Default: 2
	# Range: > 1
	max = 64

[medium]
	#Defined the max amount of running recipes
	# Default: 25
	# Range: > 1
	max = 256

[advanced]
	#Defined the max amount of running recipes
	# Default: 50
	# Range: > 1
	max = 1024

[ultimate]
	#Defined the max amount of running recipes
	# Default: 100
	# Range: > 1
	max = 4096

[max]
	#Defined the max amount of running recipes
	# Default: 256
	# Range: > 1
	max = 16384
